/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import negocios.Cliente;
import percistencia.ControlaClientes;

/**
 *
 * @author Joao
 */
public class Relato extends javax.swing.JDialog {
    private int contador = 2;
    ControlaClientes cc; 
    private String nomepass;
    /**
     * Creates new form Relato
     */
    public Relato(java.awt.Frame parent, boolean modal, ControlaClientes cc) {
        super(parent, modal);
        this.cc = cc;
        initComponents();
        iniciar();
    }

    Relato(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void iniciar(){
        
        Cliente cliente = new Cliente();
        ArrayList<Cliente> clientes = cc.retornarTodos();

           for (int o = 0; o <clientes.size(); o++){

                DefaultTableModel dtmProdutos = (DefaultTableModel) tbln.getModel();
                Object[] dados = {clientes.get(o).getNome(),clientes.get(o).getValTotal()};
                dtmProdutos.addRow(dados);
                
            }
        
        
        
        
        
        
        
        
        
        ArrayList<String> linhas = new ArrayList<String>();
        String total = null;
        String linha = new String();
        String Narquivo2 = "C:\\Users\\pmbon\\OneDrive\\Documents\\NetBeansProjects\\Cadastro\\RelatorioClientes.txt";
        File arq = new File(Narquivo2);
        
        if(arq.exists()){
        try{
            FileReader leitorDearquivo = new FileReader(Narquivo2);
            BufferedReader bufferDeArquivo = new BufferedReader(leitorDearquivo);
            
            while(true){
                
                linha =  bufferDeArquivo.readLine();
                linhas.add(linha);
                if (linha == null){
                    break;
                }
            
            }
            
        }catch(Exception e){
            }
        
        }
        
        txtrel.setText(linhas.get(1));
        txtrel1.setText(linhas.get(2));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtrel = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();
        prox = new javax.swing.JButton();
        txtrel1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbln = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Relatorio Clientes");

        txtrel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        voltar.setText("<-- Voltar");
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });

        prox.setText("Proximo -->");
        prox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proxMouseClicked(evt);
            }
        });

        txtrel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(prox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtrel, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtrel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtrel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prox, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        tbln.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Gastos"
            }
        ));
        jScrollPane1.setViewportView(tbln);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proxMouseClicked
        
        
        Cliente cliente = new Cliente();

        ArrayList<String> linhas = new ArrayList<String>();
        String total = null;
        String linha = new String();
        String Narquivo2 = "C:\\Users\\pmbon\\OneDrive\\Documents\\NetBeansProjects\\Cadastro\\RelatorioClientes.txt";
        File arq = new File(Narquivo2);
        
        if(arq.exists()){
        try{
            FileReader leitorDearquivo = new FileReader(Narquivo2);
            BufferedReader bufferDeArquivo = new BufferedReader(leitorDearquivo);
            
            while(true){
                
                linha =  bufferDeArquivo.readLine();
                linhas.add(linha);
                if (linha == null){
                    break;
                }
            
            }
            
        }catch(Exception e){
            }
        
        }
        
        
        
        contador = contador + 1; 
             
        
        txtrel.setText(linhas.get(contador));
        txtrel1.setText(linhas.get(contador + 1));
        
        contador = contador + 1; 
        //aqui da para ficar a leitura do txt e criacao do array
    
    }//GEN-LAST:event_proxMouseClicked

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        
                Cliente cliente = new Cliente();

        ArrayList<String> linhas = new ArrayList<String>();
        String total = null;
        String linha = new String();
        String Narquivo2 = "C:\\Users\\pmbon\\OneDrive\\Documents\\NetBeansProjects\\Cadastro\\RelatorioClientes.txt";
        File arq = new File(Narquivo2);
        
        if(arq.exists()){
        try{
            FileReader leitorDearquivo = new FileReader(Narquivo2);
            BufferedReader bufferDeArquivo = new BufferedReader(leitorDearquivo);
            
            while(true){
                
                linha =  bufferDeArquivo.readLine();
                linhas.add(linha);
                if (linha == null){
                    break;
                }
            
            }
            
        }catch(Exception e){
            }
        
        }
        
        
        
        contador = contador - 1; 
             txtrel.setText(linhas.get(contador));
             txtrel1.setText(linhas.get(contador + 1));
        contador = contador - 1;
    }//GEN-LAST:event_voltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Relato dialog = new Relato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prox;
    private javax.swing.JTable tbln;
    private javax.swing.JTextField txtrel;
    private javax.swing.JTextField txtrel1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
